force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <label>Currency</label>
    <nameField>
        <label>Currency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Business unit of person who reports the lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>APPS</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>DPS</fullName>
            </value>
            <value>
                <fullName>No BU found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amount_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Amount_Calculated__c</fullName>
    <formula>Consultants__c * Months__c *20*7.5*1400</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Calculated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amount_Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Amount_Old_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used for calculating the Amount using months and consultants in a separate formula. Jessie does not know how it works or how it is used, but it works so leaving it for now. January 2025</description>
    <label>Amount Old Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/force-app/main/default/objects/Opportunity/fields/BU_Lead__c.field-meta.xml
<CustomField>
    <fullName>BU_Lead__c</fullName>
    <inlineHelpText>When several BU’s are involved, BU Lead indicates case owner, indicating it as potentially largest revenue, major competence provider or other. Information is required from stage 1 - Possibility</inlineHelpText>
    <label>BU Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPS</fullName>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>DPS</fullName>
            </value>
            <value>
                <fullName>Biometrics</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
                <isActive>false</isActive>
                <label>BC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <inlineHelpText>Select the BU’s that could be a part of the Opportunity.
This field is not required for the stages 
“Planning” and “Closed”</inlineHelpText>
    <label>Business Unit</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Consultants__c.field-meta.xml
<CustomField>
    <fullName>Consultants__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The total number of consultants you believe this deal will include, measured in FTE (Full Time Equivalent)</inlineHelpText>
    <label># Consultants</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>TEXT(Owner.Currency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EUR_Rate__c.field-meta.xml
<CustomField>
    <fullName>EUR_Rate__c</fullName>
    <label>EUR Rate</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Months__c.field-meta.xml
<CustomField>
    <fullName>Months__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total duration of the contract, including options if these are likely to occur. Note: #months need to be consistent with amount.</inlineHelpText>
    <label># Months</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status for current Stage. Required for Stages 2 - RFI, 3 - Prequal and 4 - Offer.    
When opportunity moves to new Stage, Status must be set to “In progress”</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <default>true</default>
                <label>-</label>
            </value>
            <value>
                <fullName>Out of Scope</fullName>
            </value>
            <value>
                <fullName>Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APPS</fullName>
    </customValue>
    <customValue>
        <fullName>Advisory</fullName>
    </customValue>
    <customValue>
        <fullName>DPS</fullName>
    </customValue>
    <customValue>
        <fullName>Biometrics</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
        <isActive>false</isActive>
        <label>BC</label>
    </customValue>
    <customValue>
        <fullName>IMCS</fullName>
        <isActive>false</isActive>
        <label>IMCS</label>
    </customValue>
    <customValue>
        <fullName>Core</fullName>
        <isActive>false</isActive>
        <label>Core</label>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>--None--</fullName>
        <isActive>false</isActive>
        <label>--None--</label>
    </customValue>
    <customValue>
        <fullName>IMOS</fullName>
        <isActive>false</isActive>
        <label>IMOS</label>
    </customValue>
    <customValue>
        <fullName>East</fullName>
        <isActive>false</isActive>
        <label>East</label>
    </customValue>
    <customValue>
        <fullName>West</fullName>
        <isActive>false</isActive>
        <label>West</label>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
        <isActive>false</isActive>
        <label>BA</label>
    </customValue>
    <customValue>
        <fullName>North</fullName>
        <isActive>false</isActive>
        <label>North</label>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestFlowOppStageChange.cls
@isTest
public class TestFlowOppStageChange {
  //test for flow Record Triggered: Opp Changes After Save

  @isTest
  static void setCurrencyRateTest() {
    // Test cannot work in package validation (build org) until Salesforce supports installing package versions using SO snapshots in PROD
    if (!UtilityService.isScratchOrg) {
      Double currencyRate = 11.34;
      Currency__c nokCurrency = new Currency__c(
              Name = 'NOK',
              Rate__c = currencyRate
      );
      insert nokCurrency;
      TestDataFactory.createOpportunitiesToTestFlows(1);
      Opportunity oneOpp = [
              SELECT CloseDate, Id, StageName, Status__c, Currency__c, EUR_Rate__c
              FROM Opportunity
              LIMIT 1
      ];
      System.debug(oneOpp.EUR_Rate__c + 'currencyOpp');
      System.assertEquals(
              currencyRate,
              oneOpp.EUR_Rate__c,
              'The currency rate has not been updated.'
      );
    } else{
      Assert.isTrue(true);
    }
  }

  //Calculate amount with amount null, months and consultants not null
  @isTest
  static void updateCalculatedAmount() {
    TestDataFactory.createOpportunitiesToTestFlows(1);
    Opportunity oneOpp = [
      SELECT Id, Amount, Consultants__c, Months__c
      FROM Opportunity
      LIMIT 1
    ];
    oneOpp.Consultants__c = 10;
    oneOpp.Months__c = 30;
    oneOpp.Amount = 0;
    update oneOpp;
    Opportunity oneOpp1 = [
      SELECT Amount_old_value__c, Id, Amount, Amount_Calculated__c
      FROM Opportunity
      WHERE Id = :oneOpp.Id
    ];
    System.assertEquals(
      oneOpp1.Amount_old_value__c,
      oneOpp1.Amount_calculated__c
    );
    System.assertEquals(oneOpp1.Amount, oneOpp1.Amount_calculated__c);
  }

  @isTest
  static void newCalculatedAmount() {
    TestDataFactory.createOpportunitiesToTestFlows(1);
    Opportunity oneOpp = [
      SELECT Id, Amount, Amount_Calculated__c, Amount_Old_Value__c
      FROM Opportunity
      LIMIT 1
    ];

    System.assertEquals(
      oneOpp.Amount_old_value__c,
      oneOpp.Amount_calculated__c
    );
    System.assertEquals(oneOpp.Amount, oneOpp.Amount_calculated__c);
  }

  @isTest
  static void singleBULead() {
    TestDataFactory.createOpportunitiesToTestFlows(1);
    Opportunity oneOpp = [
      SELECT BU_Lead__c, StageName, Business_Unit__c
      FROM Opportunity
      LIMIT 1
    ];
    oneOpp.StageName = '2 - RFI';
    update oneOpp;
    System.debug(oneOpp.Bu_Lead__c);
    Opportunity oneOpp1 = [
      SELECT BU_Lead__c, StageName
      FROM Opportunity
      WHERE Id = :oneOpp.Id
      LIMIT 1
    ];
    System.assertEquals(
      Utils.APPS,
      oneopp1.BU_Lead__c,
      'BU Lead should be APPS'
    );
  }

  @isTest
  static void twoBULeads() {
    Test.StartTest();
    TestDataFactory.createOpportunitiesToTestFlowsWithTwoBuLeads(1);
    Test.StopTest();
    Opportunity oneOpp = [
      SELECT BU_Lead__c, StageName, Business_Unit__c
      FROM Opportunity
      LIMIT 1
    ];
    System.debug(oneOpp.Business_Unit__c);
    System.assertEquals(
      null,
      oneopp.BU_Lead__c,
      'There should not be a BU Lead'
    );
  }
}