force-app/force-app/main/default/objects/Opportunity/fields/BU_Lead__c.field-meta.xml
<CustomField>
    <fullName>BU_Lead__c</fullName>
    <inlineHelpText>When several BU’s are involved, BU Lead indicates case owner, indicating it as potentially largest revenue, major competence provider or other. Information is required from stage 1 - Possibility</inlineHelpText>
    <label>BU Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPS</fullName>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>DPS</fullName>
            </value>
            <value>
                <fullName>Biometrics</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
                <isActive>false</isActive>
                <label>BC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <inlineHelpText>Select the BU’s that could be a part of the Opportunity.
This field is not required for the stages 
“Planning” and “Closed”</inlineHelpText>
    <label>Business Unit</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit_Count__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Count__c</fullName>
    <formula>IF(INCLUDES(Business_Unit__c, &quot;APPS&quot;), 1, 0 ) + 
IF(INCLUDES(Business_Unit__c, &quot;Advisory&quot;), 1, 0 ) + 
IF(INCLUDES(Business_Unit__c, &quot;DPS&quot; ) , 1, 0) +
IF(INCLUDES(Business_Unit__c, &quot;BD&quot; ) , 1, 0) +
IF(INCLUDES(Business_Unit__c, &quot;Biometrics&quot; ) , 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APPS</fullName>
    </customValue>
    <customValue>
        <fullName>Advisory</fullName>
    </customValue>
    <customValue>
        <fullName>DPS</fullName>
    </customValue>
    <customValue>
        <fullName>Biometrics</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
        <isActive>false</isActive>
        <label>BC</label>
    </customValue>
    <customValue>
        <fullName>IMCS</fullName>
        <isActive>false</isActive>
        <label>IMCS</label>
    </customValue>
    <customValue>
        <fullName>Core</fullName>
        <isActive>false</isActive>
        <label>Core</label>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>--None--</fullName>
        <isActive>false</isActive>
        <label>--None--</label>
    </customValue>
    <customValue>
        <fullName>IMOS</fullName>
        <isActive>false</isActive>
        <label>IMOS</label>
    </customValue>
    <customValue>
        <fullName>East</fullName>
        <isActive>false</isActive>
        <label>East</label>
    </customValue>
    <customValue>
        <fullName>West</fullName>
        <isActive>false</isActive>
        <label>West</label>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
        <isActive>false</isActive>
        <label>BA</label>
    </customValue>
    <customValue>
        <fullName>North</fullName>
        <isActive>false</isActive>
        <label>North</label>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/force-app/main/default/classes/processes/tests/OpportunityUpdateBULeadTest.cls
@isTest
public with sharing class OpportunityUpdateBULeadTest {

    @TestSetup
    static void createTestData() {
        Opportunity opportunity = TestDataFactory.createOpportunity();
    }

    @IsTest
    static void updateBusinessUnitTest() {
        Opportunity opportunity = [SELECT Id, Business_Unit__c, Business_Unit_Count__c, BU_Lead__c, StageName FROM Opportunity LIMIT 1];
        System.debug(opportunity);

        Test.startTest();
        opportunity.Business_Unit__c = Utils.APPS;
        update opportunity;
        Test.stopTest();

        Opportunity opportunityAfterUpdate = [SELECT Id, Business_Unit__c, Business_Unit_Count__c, BU_Lead__c, StageName FROM Opportunity LIMIT 1];
        System.assert(opportunityAfterUpdate.BU_Lead__c == Utils.APPS);
    }
}