force-app/main/default/objects/Account/fields/Apps_Owner__c.field-meta.xml
<CustomField>
    <fullName>Apps_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apps Client Developer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Business_Unit__c</field>
            <operation>equals</operation>
            <value>APPS</value>
        </filterItems>
        <filterItems>
            <field>User.Business_Unit__c</field>
            <operation>equals</operation>
            <value>Business Value Services</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>APPSOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Account/fields/BC_Owner__c.field-meta.xml
<CustomField>
    <fullName>BC_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advisory Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Business_Unit__c</field>
            <operation>equals</operation>
            <value>Advisory</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>BCOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DPS_Owner__c.field-meta.xml
<CustomField>
    <fullName>DPS_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPS Client Developer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Business_Unit__c</field>
            <operation>equals</operation>
            <value>DPS</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Apps_Owner__c.field-meta.xml
<CustomField>
    <fullName>Apps_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The bid owner in Apps. Is automatically populated with the Apps owner who is registered on the Account in Salesforce, but this can be manually overridden.</description>
    <inlineHelpText>Manager that has the overall responsibility for the opportunity, should be a  a member from LG Core or Delivery. Responsible for driving the tender forward, onboarding the right team, delivering on time with high quality. Also responsible for reporting and escalating progress and risk.</inlineHelpText>
    <label>Apps Opportunity Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BC_Owner__c.field-meta.xml
<CustomField>
    <fullName>BC_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The bid owner in BC. Is automatically populated with the Apps owner who is registered on the Account in Salesforce, but this can be manually overridden.</description>
    <inlineHelpText>Opportunity’s owner, will normally be the client owner in Advisory or other roles in Advisory with sales and bid responsibility. Responsible for driving the opportunity forward, customer meetings, creating value proposition, getting bid staff in place, ensuring that the offer is competitive with high quality, acceptable risk and good commercial terms. Responsible to share updates in Salesforce. Escalates to suitable forums, e.g. status meeting, bid meeting or sales meeting, and taking measures.</inlineHelpText>
    <label>Advisory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BC_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DPS_Owner__c.field-meta.xml
<CustomField>
    <fullName>DPS_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account Manager in DPS Management group, assigned to Priority- and Hunting accounts. The role is responsible for Relationship Management during the sales process. The field is inherited from Client object in SF</inlineHelpText>
    <label>DPS Client Developer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DPS_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeactivateUser.cls
public class DeactivateUser {
  public static void main(List<User> userList) {
    List<Account> accountList = new List<Account>();
    List<Opportunity> opportunityList = new List<Opportunity>();
    List<ID> UserIds = new List<ID>();

    for (User usr : userList) {
      UserIds.add(usr.ID);

      accountList = [
        SELECT ID, Name, OwnerID, APPS_Owner__c, BC_Owner__c, DPS_Owner__c
        FROM Account
        WHERE
          OwnerID IN :UserIDs
          OR APPS_Owner__c IN :UserIDs
          OR BC_Owner__c IN :UserIDs
          OR DPS_Owner__c IN :UserIDs
      ];
      opportunityList = [
        SELECT
          ID,
          Description,
          OwnerID,
          APPS_Owner__c,
          BC_Owner__c,
          DPS_Owner__c
        FROM Opportunity
        WHERE
          (OwnerID IN :UserIDs
          OR APPS_Owner__c IN :UserIDs
          OR BC_Owner__c IN :UserIDs
          OR DPS_Owner__c IN :UserIDs)
          AND IsClosed = FALSE
      ];

      if (
        (accountList.size() > 0 || opportunityList.size() > 0) &
        usr.IsActive == false
      ) {
        String msg =
          'The User is owner or BU owner for ' +
          accountList.size() +
          ' accounts and ' +
          opportunityList.size() +
          ' opportunities. Reassign ownerships before you deactivate. (This is a trigger.)';
        usr.addError(msg);
      }
    }
  }
}