force-app/main/default/objects/Account/fields/Apps_Owner__c.field-meta.xml
<CustomField>
    <fullName>Apps_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apps Client Developer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Business_Unit__c</field>
            <operation>equals</operation>
            <value>APPS</value>
        </filterItems>
        <filterItems>
            <field>User.Business_Unit__c</field>
            <operation>equals</operation>
            <value>Business Value Services</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>APPSOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <inlineHelpText>Can only be modified in Navision</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Faroes</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Great Britain</fullName>
            </value>
            <value>
                <fullName>Iceland</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malta</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/main/default/objects/Account/fields/Org_number__c.field-meta.xml
<CustomField>
    <fullName>Org_number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Official Orgnumber. Can only be modified in Navision</inlineHelpText>
    <label>Org. number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/force-app/main/default/objects/Bid__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Before you can convert the lead, it must be linked to an existing Account.
If you don&apos;t find your account, you can create one with the &quot;New Account&quot; button at the top og this page.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Business unit of person who reports the lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>APPS</fullName>
            </value>
            <value>
                <fullName>BC</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>DPS</fullName>
            </value>
            <value>
                <fullName>No BU found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Norway</fullName>
                <default>true</default>
                <label>Norway</label>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Great Britain</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Org_number__c.field-meta.xml
<CustomField>
    <fullName>Org_number__c</fullName>
    <inlineHelpText>Org number must be in this format:
NO: 9 pos. numeric,
DK: 8 pos. numeric,
SE: 6 pos. numeric + &quot;-&quot; + 4 pos. numeric. No space characters allowed.</inlineHelpText>
    <label>Org. number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Apps_Owner__c.field-meta.xml
<CustomField>
    <fullName>Apps_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The bid owner in Apps. Is automatically populated with the Apps owner who is registered on the Account in Salesforce, but this can be manually overridden.</description>
    <inlineHelpText>Manager that has the overall responsibility for the opportunity, should be a  a member from LG Core or Delivery. Responsible for driving the tender forward, onboarding the right team, delivering on time with high quality. Also responsible for reporting and escalating progress and risk.</inlineHelpText>
    <label>Apps Opportunity Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <inlineHelpText>Select the BU’s that could be a part of the Opportunity.
This field is not required for the stages 
“Planning” and “Closed”</inlineHelpText>
    <label>Business Unit</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Consultants__c.field-meta.xml
<CustomField>
    <fullName>Consultants__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The total number of consultants you believe this deal will include, measured in FTE (Full Time Equivalent)</inlineHelpText>
    <label># Consultants</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/force-app/main/default/objects/Opportunity/fields/Contract_Category__c.field-meta.xml
<CustomField>
    <fullName>Contract_Category__c</fullName>
    <inlineHelpText>Type of contract. This field is required for all opportunity types e x c e p t Frame agreement and Capacity agreement. This field is dependent on Type.
Select which contract category this opportunity is. If it is a new call off or change, the framework agreement is selected by the “add contract” button.</inlineHelpText>
    <label>Contract Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New contract (not connected to framework/capacity agreement)</fullName>
            </value>
            <value>
                <fullName>Call Off</fullName>
            </value>
            <value>
                <fullName>Change to an active call off or contract</fullName>
            </value>
            <value>
                <fullName>New call off (Agreement on existing contract)</fullName>
            </value>
            <value>
                <fullName>Capacity agreement</fullName>
                <isActive>false</isActive>
                <label>Capacity agreement</label>
            </value>
            <value>
                <fullName>Frame Agreement</fullName>
                <isActive>false</isActive>
                <label>Frame Agreement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Months__c.field-meta.xml
<CustomField>
    <fullName>Months__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total duration of the contract, including options if these are likely to occur. Note: #months need to be consistent with amount.</inlineHelpText>
    <label># Months</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Proposal_Due_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Due_Date_Time__c</fullName>
    <inlineHelpText>Deadline for handing in the offer. 
The Opportunity owner will receive notification emails: one week before due date and one day before due date.
A value is required in this field when &quot;Stage&quot; is past &quot;0 - Planning&quot; and &quot;Status&quot; = &quot;In Progress&quot;</inlineHelpText>
    <label>Due Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status for current Stage. Required for Stages 2 - RFI, 3 - Prequal and 4 - Offer.    
When opportunity moves to new Stage, Status must be set to “In progress”</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <default>true</default>
                <label>-</label>
            </value>
            <value>
                <fullName>Out of Scope</fullName>
            </value>
            <value>
                <fullName>Capacity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>APPS</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Business Value Services</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>DPS</fullName>
            </value>
            <value>
                <fullName>Eggs Part of Sopra Steria</fullName>
            </value>
            <value>
                <fullName>Market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APPS</fullName>
    </customValue>
    <customValue>
        <fullName>Advisory</fullName>
    </customValue>
    <customValue>
        <fullName>DPS</fullName>
    </customValue>
    <customValue>
        <fullName>Biometrics</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
        <isActive>false</isActive>
        <label>BC</label>
    </customValue>
    <customValue>
        <fullName>IMCS</fullName>
        <isActive>false</isActive>
        <label>IMCS</label>
    </customValue>
    <customValue>
        <fullName>Core</fullName>
        <isActive>false</isActive>
        <label>Core</label>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <isActive>false</isActive>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>--None--</fullName>
        <isActive>false</isActive>
        <label>--None--</label>
    </customValue>
    <customValue>
        <fullName>IMOS</fullName>
        <isActive>false</isActive>
        <label>IMOS</label>
    </customValue>
    <customValue>
        <fullName>East</fullName>
        <isActive>false</isActive>
        <label>East</label>
    </customValue>
    <customValue>
        <fullName>West</fullName>
        <isActive>false</isActive>
        <label>West</label>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
        <isActive>false</isActive>
        <label>BA</label>
    </customValue>
    <customValue>
        <fullName>North</fullName>
        <isActive>false</isActive>
        <label>North</label>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/* 31.3.25 Using a separate class TestDataInsertUser to create the user
that owns opportunities
 */
@IsTest
public class TestDataFactory {
    public class MockException extends Exception {
    }

    public static List<Opportunity> createOpportunities(Integer numberOfRecords, Boolean doInsert, Boolean addMockId) {
        if (doInsert && addMockId) {
            throw new MockException('Cannot add Mock Id to inserted record!');
        }
        List<Opportunity> opportunities = new List<Opportunity>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Opportunity opportunity = new Opportunity(
                Id = addMockId ? generateFakeId(Opportunity.SObjectType) : null,
                AccountId = createAccount(doInsert, addMockId).Id,
                Name = 'Test Opportunity ' + i,
                StageName = '1 - Possibility',
                Status__c = '-',
                Business_Unit__c = 'APPS',
                Contract_Category__c = 'New contract (not connected to framework/capacity agreement)',
                CloseDate = Date.today() + 1,
                Consultants__c = 1,
                Months__c = 1,
                Proposal_Due_Date_Time__c = DateTime.now(),
                Type = 'Frame Agreement'
            );
            opportunities.add(opportunity);
        }
        if (doInsert) {
            insert opportunities;
        }
        return opportunities;
    }

    public static List<Account> createAccounts(Integer numberOfRecords, Boolean doInsert, Boolean addMockId) {
        if (doInsert && addMockId) {
            throw new MockException('Cannot add Mock Id to inserted record!');
        }
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            accounts.add(
                new Account(
                    Id = addMockId ? generateFakeId(Account.SObjectType) : null,
                    Name = (Math.random() * 10).format() + 'Client Name',
                    Country__c = 'Norway',
                    Apps_Owner__c = UserInfo.getUserId()
                )
            );
        }
        if (doInsert) {
            insert accounts;
        }
        return accounts;
    }

    public static Account createAccount(Boolean doInsert, Boolean addMockId) {
        /*Database.DMLOptions dml = new Database.DMLOptions();
	dml.DuplicateRuleHeader.allowSave = true; //Controlls bypass
	dml.DuplicateRuleHeader.runAsCurrentUser = true;*/
        Account account = new Account(
            Id = addMockId ? generateFakeId(Account.SObjectType) : null,
            Name = (Math.random() * 10).format() + 'Client Name',
            Country__c = 'Norway',
            Apps_Owner__c = UserInfo.getUserId()
        );
        if (doInsert) {
            insert account;
        }
        return account;
    }

    public static List<Opportunity> createOpportunities(Integer numberOfOpportunities) {
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true; //Controlls bypass
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        Account a = createAccount();
        List<Opportunity> result = new List<Opportunity>();
        for (Integer i = 0; i < numberOfOpportunities; i++) {
            result.add(
                new Opportunity(
                    Name = 'TestDataFactoryTestOpportunity12345',
                    StageName = '1 - Possibility',
                    Status__c = '-',
                    Business_Unit__c = 'APPS',
                    Contract_Category__c = 'New contract (not connected to framework/capacity agreement)',
                    CloseDate = Date.today() + 1,
                    Consultants__c = 1,
                    Months__c = 1,
                    AccountID = a.Id,
                    Proposal_Due_Date_Time__c = DateTime.now(),
                    Type = 'Frame Agreement'
                )
            );
        }

        insert result;
        return result;
    }

    public static List<Opportunity> createOpportunitiesToTestFlows(Integer numberOfOpportunities) {
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true; //Controlls bypass
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        Account a = createAccount();
        List<Opportunity> result = new List<Opportunity>();
        for (Integer i = 0; i < numberOfOpportunities; i++) {
            result.add(
                new Opportunity(
                    Name = 'Opportunities Testing Flows',
                    StageName = '1 - Possibility',
                    Status__c = '-',
                    Business_Unit__c = 'APPS',
                    CloseDate = Date.today() + 30,
                    Consultants__c = 2,
                    Months__c = 1,
                    AccountID = a.Id,
                    Type = 'Frame Agreement'
                )
            );
        }

        insert result;
        return result;
    }

    public static List<Opportunity> createOpportunitiesToTestFlowsWithTwoBuLeads(Integer numberOfOpportunities) {
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true; //Controlls bypass
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        Account a = createAccount();
        List<Opportunity> result = new List<Opportunity>();
        for (Integer i = 0; i < numberOfOpportunities; i++) {
            result.add(
                new Opportunity(
                    Name = 'Opportunities Testing Flows',
                    StageName = '1 - Possibility',
                    Status__c = '-',
                    Business_Unit__c = 'APPS;DPS;',
                    CloseDate = Date.today() + 30,
                    Consultants__c = 2,
                    Months__c = 1,
                    AccountID = a.Id,
                    Type = 'Frame Agreement'
                )
            );
        }

        insert result;
        return result;
    }

    public static Opportunity createOpportunity() {
        List<Opportunity> opportunities = createOpportunities(1);
        return opportunities[0];
    }

    public static Opportunity createOpportunityWithBidRoom() {
        Account a = createAccount();
        Opportunity result = new Opportunity(
            Name = 'TestDataFactoryTestOpportunity12345',
            StageName = '1 - Possibility',
            Status__c = '-',
            Business_Unit__c = 'APPS',
            CloseDate = Date.today(),
            Consultants__c = 1,
            Months__c = 1,
            AccountID = a.Id,
            Proposal_Due_Date_Time__c = DateTime.now()
        );
        result.Bid_Number__c = 'https://steria.sharepoint.com/sites/intra_sc_tilbud1/110';

        insert result;
        return result;
    }

    public static List<Bid__c> createBids(Integer numberOfBids) {
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true; //Controlls bypass
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        Account a = createAccount();
        Opportunity o = createOpportunity();

        List<Bid__c> result = new List<Bid__c>();
        for (Integer i = 0; i < numberOfBids; i++) {
            //         result.add(new Bid__c(Opportunity__c = o.Id, BID_Number__c = '1'));
            result.add(new Bid__c(Opportunity__c = o.Id, BID_Number__c = i.format()));
        }

        insert result;
        return result;
    }
    //public static Bid__c createBid() {
    //List<Bid__c> Bids = createBids(1);
    //return BidsWithoutUrl[0];
    //}
    public static List<Bid__c> createBidsWithoutBidUrl(Integer numberOfBids) {
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true; //Controlls bypass
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        Account a = createAccount();
        Opportunity o = createOpportunity();

        List<Bid__c> result = new List<Bid__c>();
        for (Integer i = 0; i < numberOfBids; i++) {
            result.add(new Bid__c(Opportunity__c = o.Id));
        }

        insert result;
        return result;
    }
    //public static Bid__c createBidWithoutURL() {
    //List<Bid__c> Bids = createBidsWithoutBidUrl(1);
    //return BidsWithoutUrl[0];
    //}

    public static Task createTask(String whatId, Boolean isClosed) {
        List<Task> result = createTasks(1, whatId, isClosed);
        return result[0];
    }

    public static List<Task> createTasks(Integer numberOfTasks, String whatId, Boolean isClosed) {
        String status = 'Open';

        if (isClosed)
            status = 'Completed';

        List<Task> result = new List<Task>();
        for (Integer i = 0; i < numberOfTasks; i++) {
            result.add(new Task(WhatId = whatId, Subject = 'Test', Status = status));
        }
        insert result;
        return result;
    }

    public static Task createTaskContact(Integer numberOfTasks, String whoId) {
        List<Task> result = createTasksContact(1, whoId);
        return result[0];
    }

    public static List<Task> createTasksContact(Integer numberOfTasks, String whoId) {
        List<Task> result = new List<Task>();
        for (Integer i = 0; i < numberOfTasks; i++) {
            result.add(new Task(WhoId = whoId, Subject = 'Test'));
        }
        insert result;
        return result;
    }

    public static Event createEventContact(Integer numberOfEvents, String whoId) {
        List<Event> result = createEventsContact(1, whoId);
        return result[0];
    }

    //public static List<Event> createEventsContact(Integer numberOfEvents, String whoId, String assignedTo, Datetime startdatetime, dateTime enddatetime) {

    public static List<Event> createEventsContact(Integer numberOfEvents, String whoId) {
        List<Event> result = new List<Event>();
        for (Integer i = 0; i < numberOfEvents; i++) {
            result.add(new Event(WhoId = whoId, Subject = 'Test', startdatetime = DateTime.now(), enddatetime = DateTime.now()));
        }
        insert result;
        return result;
    }

    public static List<Account> createAccounts(Integer numberOfAccounts) {
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true; //Controlls bypass
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        List<Account> result = new List<Account>();
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        // Insert account as current user
        System.runAs(thisUser) {
            User u = createUser();
            for (Integer i = 0; i < numberOfAccounts; i++) {
                Integer m = numberOfAccounts;
                m = m + 1;
                result.add(new Account(Name = (Math.random() * 10).format() + 'Client Name', Country__c = 'Norway', Apps_Owner__c = u.Id));
            }
            insert result;
        }
        return result;
    }

    public static Account createAccount() {
        TriggerHandler.bypass('AccountTriggerHandler');
        List<Account> result = createAccounts(1);
        return result[0];
    }

    public static List<Contact> createContacts(Integer numberOfContacts) {
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true; //Controlls bypass
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        Account a = createAccount();
        List<Contact> result = new List<Contact>();

        for (Integer i = 0; i < numberOfContacts; i++) {
            Integer m = numberOfContacts;
            m = m + 1;
            result.add(
                new Contact(FirstName = (Math.random() * 10).format() + 'First Name', LastName = (Math.random() * 10).format() + 'Last Name', AccountId = a.Id, Email = 'cuddlypuppy' + i + '@aol.com')
            );
        }
        insert result;
        return result;
    }

    public static Contact createContact() {
        //  Account a=createAccount();
        List<Contact> result = createContacts(1);
        return result[0];
    }

    public static User createUser() {
        testDataInsertUser.insertUser(1);
        List<User> result = [
            SELECT Id, Alias, Email
            FROM User
            WHERE Alias LIKE '%testu%' AND Email LIKE '%test@example.com%'
        ];
        return result[0];
    }

    public static List<User> createUsers(Integer i) {
        testDataInsertUser.insertUser(i);
        List<User> result = [
            SELECT Id, Alias, Email
            FROM User
            WHERE Alias LIKE '%testu%' AND Email LIKE '%test@example.com%'
        ];
        return result;
    }

    public static Account createAccountWithCheckInBrreg(Boolean shouldInsert, String accountOrgNumber) {
        Account account = new Account(Name = 'Test account', Org_number__c = accountOrgNumber, Country__c = 'Norway');
        if (shouldInsert) {
            insert account;
        }
        return account;
    }
    public static Lead createLead(Boolean shouldInsert, Id accountId) {
        Lead lead = new Lead(FirstName = 'Test', LastName = 'Test LastName', Company = 'Company Test', Account__c = accountId);
        if (shouldInsert) {
            insert lead;
        }
        return lead;
    }

    private static Integer mockIncrement=0;
    private static Integer getMockIncrement(){
        mockIncrement++;
        return mockIncrement;
    }
    //https://salesforce.stackexchange.com/questions/21137/creating-unit-tests-without-interacting-with-the-database-creating-fake-ids
    public static String generateFakeId(Schema.SObjectType sObjectType) {
        String result = String.valueOf(getMockIncrement());
        return sObjectType.getDescribe().getKeyPrefix() + '0'.repeat(12 - result.length()) + result;
    }
}