force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>APPS</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Business Value Services</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>DPS</fullName>
            </value>
            <value>
                <fullName>Eggs Part of Sopra Steria</fullName>
            </value>
            <value>
                <fullName>Market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <description>For bid-portal</description>
    <inlineHelpText>Correct email address from AD (firstname.lastname@soprasteria.com) The field is needed for the BID portal integration.</inlineHelpText>
    <label>Email2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/TestDataInsertUser.cls
public class TestDataInsertUser {
  public static void insertUser(Integer numberOfUsers) {
    List<User> result = new List<User>();
    Integer n = numberOfUsers;
    for (Integer i = 0; i < numberOfUsers; i++) {
      n = n + 1;
      String orgId = UserInfo.getOrganizationId();
      String dateString = String.valueof(Datetime.now())
        .replace(' ', '')
        .replace(':', '')
        .replace('-', '');
      Integer randomInt = Integer.valueOf(math.rint(math.random() * 1000000));
      Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
      String uniqueName = orgId + dateString + randomInt;
      result.add(
        new User(
          Alias = 'testu' + n,
          Email = 'test@example.com' + n,
          Email2__c = 'test@example.com' + n,
          Country = 'Norway',
          EmailEncodingKey = 'ISO-8859-1',
          LastName = 'Test',
          LanguageLocaleKey = 'en_US',
          LocaleSidKey = 'no_NO',
          TimeZoneSidKey = 'Europe/Paris',
          ProfileId = p.Id,
          UserName = 'test' + uniqueName + '@soprasteriaxTest.com',
          Business_Unit__c = 'APPS',
          IsActive = true
        )
      );
    }

    insert result;
  }
}