force-app/main/default/objects/Opportunity/fields/Contract_Price_Model__c.field-meta.xml
<CustomField>
    <fullName>Contract_Price_Model__c</fullName>
    <label>Price / Delivery Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed price/Target price</fullName>
            </value>
            <value>
                <fullName>T&amp;M (No estimates or cap)</fullName>
            </value>
            <value>
                <fullName>T&amp;M with estimates / delivery responsibility</fullName>
            </value>
            <value>
                <fullName>SW/Solution delivery</fullName>
            </value>
            <value>
                <fullName>FAST</fullName>
            </value>
            <value>
                <fullName>T&amp;M delivery responsibility</fullName>
                <isActive>false</isActive>
                <label>T&amp;M delivery responsibility</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_4_Date__c.field-meta.xml
<CustomField>
    <fullName>Stage_4_Date__c</fullName>
    <description>The date the opportunity reaches stage 4 - Offer</description>
    <label>Stage 4 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/setOpportunityHistory.cls
//batch

public class setOpportunityHistory {
  public static Date myDate;
  public static void stage4(Id myOppId) {
    List<Opportunity> updateOpps = new List<Opportunity>();
    List<Opportunity> myOpps = [
      SELECT Id, Name
      FROM Opportunity
      WHERE Id = :myOppId
      //Calendar_YEAR(DashboardsGSP__Last_Stage_Change_Date__c) = 2024
      //AND StageName = '4 -Offer'
      //AND Contract_Price_Model__c != ''
      //LIMIT 10
    ];
    for (Opportunity record : myOpps) {
      for (OpportunityHistory ofh : [
        SELECT Id, CreatedDate, OpportunityId, StageName
        FROM OpportunityHistory
        WHERE
          StageName = '4 - Offer'
          AND Calendar_Year(CreatedDate) = 2024
          AND OpportunityId = :record.id
        ORDER BY CreatedDate DESC
        LIMIT 1
      ]) {
        myDate = ofh.CreatedDate.Date();
        System.debug('my date:' + myDate);
        record.Stage_4_Date__c = myDate;
        updateOpps.add(record);
      }
      update updateOpps;
    }
  }
}