force-app/force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <inlineHelpText>Can only be modified in Navision</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Faroes</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Great Britain</fullName>
            </value>
            <value>
                <fullName>Iceland</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malta</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/main/default/objects/Account/fields/Org_number__c.field-meta.xml
<CustomField>
    <fullName>Org_number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Official Orgnumber. Can only be modified in Navision</inlineHelpText>
    <label>Org. number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DnBGetCreditRating.cls
public with sharing class DnBGetCreditRating {

    public final static String ERR_MSG_UNSUPPORTED_COUNTRY = 'Country is not supported for credit check';
    public final static String ERR_MSG_ORN_NUM_REQUIRED = 'Org Number is required for credit check';

    public static Map<String, String> country2urlSuffix = new Map<String, String> {
        'Norway' => 'no',
        'Sweden' => 'se',
        'Finland' => 'fi',
        'Denmark' => 'dk'
    };

    @InvocableMethod
    public static List<FlowResponse> getCreditRatingInvocable(List<String> recordIds) {
        try {

            Account account = [SELECT Id, Org_number__c, Country__c FROM Account WHERE Id = :recordIds[0]];

            if (!country2urlSuffix.containsKey(account.Country__c)) {
                return new List<FlowResponse> { new FlowResponse(false, ERR_MSG_UNSUPPORTED_COUNTRY) };
            }

            if (String.isBlank(account.Org_number__c)) {
                return new List<FlowResponse> { new FlowResponse(false, ERR_MSG_ORN_NUM_REQUIRED) };
            }

            Response response = getCreditRating(sanitizeOrgNum(account.Org_number__c), country2urlSuffix.get(account.Country__c));
            String message;

//            if (response.success) {
//            message = ((CreditRatingResponse)response.data).risk.creditRatings.currentCreditRating.code  + '  ' + 
//                           ((CreditRatingResponse)response.data).risk.creditRatings.currentCreditRating.annualReportDate.year + '-' +
//                           ((CreditRatingResponse)response.data).risk.creditRatings.currentCreditRating.annualReportDate.month; 
//                           }
            if (response.success) {
                message = ((CreditRatingResponse)response.data).risk.creditRatings.currentCreditRating.code;
            }
            else {
                message = ((ErrorResponse)response.data).message;
            }

            return new List<FlowResponse> { new FlowResponse(response.success, message) };
        }
        catch (Exception ex) {
            return new List<FlowResponse> { new FlowResponse(false, ex.getMessage()) };
        }
    }

    private static String sanitizeOrgNum(String orgNum) {
        return orgNum.replace('-', '');
    }

    public class FlowResponse {
        @InvocableVariable(Label='success' Description='success' Required=true)
        public Boolean success;

        @InvocableVariable(Label='message' Description='message' Required=true)
        public String message;

        public FlowResponse(Boolean success, String message) {
            this.success = success;
            this.message = message;
        }
    }

    public static Response getCreditRating(String regNum, String countryUrlSuffix) {

        CreditRatingRequest request = new CreditRatingRequest(regNum);

        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:DnBCallouts/credit-data-companies/v2/companies/' + countryUrlSuffix);
        req.setHeader('Content-Type', 'application/json');
        req.setMethod('POST');
        req.setBody(JSON.serialize(request));
        HttpResponse res = new Http().send(req);

        System.debug(res.getBody());

        if (res.getStatusCode() == 200) {
            CreditRatingResponse data = (CreditRatingResponse)JSON.deserialize(res.getBody(), CreditRatingResponse.class);
            return new Response(true, data);
        }
        else {
            ErrorResponse data = (ErrorResponse)JSON.deserialize(res.getBody(), ErrorResponse.class);
            return new Response(false, data);
        }
    }

    public class CreditRatingRequest {
        public String registrationNumber;
        public String language;
        public List<Segment> segments;

        public CreditRatingRequest(String regNum) {
            this.registrationNumber = regNum;
            this.language = 'EN';
            this.segments = new List<Segment> {
                Segment.RISK,
                Segment.FINANCE
            };
        }
    }

    public enum Segment { RISK, FINANCE, MANAGEMENT, OWNERSHIP, EVENTS }

    public class Response {
        public Boolean success;
        public Object data;

        public Response(Boolean success, Object data) {
            this.success = success;
            this.data = data;
        }
    }

    public class CreditRatingResponse {
        Risk risk;
    }

    public class Risk {
        CreditRatings creditRatings;
    }

    public class CreditRatings {
        CurrentCreditRating currentCreditRating;
    }

    public class CurrentCreditRating {
        AnnualReportDate annualReportDate;
        public String code; //AAA, AA, A, B, C, AN, -
        public String description;
    }
    
    public class AnnualReportDate {
        public String year;
        public String month;
    }

    public class ErrorResponse {
        public Integer status;
        public String statusText;
        public String timestamp;
        public String message;
        public List<SubError> subErrors;
    }

    public class SubError {
        public String size;
        public String rejectedValue;
        public String message;
    }
}